main code
S-MOHSEN-SH/microservice_bookshop pull request #1
Opened 2024-07-09 13:09 UTC by S-MOHSEN-SH

2024-07-12 10:05 UTC, InnoMikitaKutas commented
Too big PR

2024-07-12 10:41 UTC, InnoMikitaKutas requested changes

2024-07-12 10:41 UTC, InnoMikitaKutas commented on .env
`.env` should be in `.gitignore` and `.dockerignore`

2024-07-12 10:41 UTC, InnoMikitaKutas commented on book/.eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
Why no explicit any off?

2024-07-12 10:41 UTC, InnoMikitaKutas commented on book/src/app.module.ts
> +        host: configService.get<string>('POSTGRES_HOST'),
You can create `config.ts`, and export object with that properties

2024-07-12 10:41 UTC, InnoMikitaKutas commented on book/src/book/book.controller.ts
> +  async showAllBooks() {
additionally you can type return value
```suggestion
  async showAllBooks(): Book[] {
```

2024-07-12 10:41 UTC, InnoMikitaKutas commented on book/src/common/dto/book.dto.ts
> +  readonly price: number;
Maybe we should validate price so it's value will not be negative

2024-07-12 10:41 UTC, InnoMikitaKutas commented on book/src/common/dto/order.dto.ts
> +  quantity: number;
Same as price

2024-07-12 10:41 UTC, InnoMikitaKutas commented on gateway/src/auth/dto/createUser.dto.ts
> +  password: string;
```suggestion
  @IsNotEmpty()
  @IsStrongPassword()
  password: string;
```

2024-07-12 10:41 UTC, InnoMikitaKutas commented on user/src/user.controller.ts
> +    console.log('i am in registeration part');
I think you forgot to delete this console log

2024-07-12 10:44 UTC, MichailZyusko reviewed
One commit for 30 000 lines of code it's too much :)

2024-07-12 10:44 UTC, MichailZyusko commented on .env
Why you have .env file in your remote github?

2024-07-12 10:44 UTC, MichailZyusko commented on book/.dockerignore
It's usually should be extended and should include TS files, readme.md, dockerfiles and others

2024-07-12 10:44 UTC, MichailZyusko commented on book/Dockerfile
> +RUN npm install
Better to use npm ci instead of npm i

2024-07-12 10:44 UTC, MichailZyusko commented on book/Dockerfile
> +FROM node:16
U can use more optimised images like node:16-alpine and others

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/app.module.ts
> +        synchronize: true,
This option should based on project env

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/book/book.controller.ts
> +  }
Which status code do you return here?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/book/book.controller.ts
> +    @Body() updateBookDto: Partial<CreateBookDto>,
```suggestion
    @Body() updateBookDto: Partial<BookDto>,
```

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/book/book.service.ts
> +  async findAll(): Promise<Book[]> {
Should we specify return type here or it should be injected automatically?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/book/book.service.ts
> +    const book = await this.findOne(id);
Did you return error in case if this book doesn't exists?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/book/book.service.ts
> +  async remove(id: number): Promise<void> {
Did you return error in case if this book doesn't exists?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/common/entity/order-item.model.ts
> +  price: number;
How to handle a case when book is pre-ordered ?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/main.ts
> +  await app.listen(5002);
Let's get port from .env file

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/main.ts
> +  await app.listen(5002);
Also U can use () => {} for listen function

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/order/order.controller.ts
> +  }
Do we have pagination, sorting, projection?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/order/order.controller.ts
Do we have functionality to update order?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/order/order.service.ts
> +    }, 0);
Can we calcilate this totalPrices on database side?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/common/entity/order-item.model.ts
> +  quantity: number;
Should be more then 1 only!

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/order/order.service.ts
> +      return acc + bookPrice * item.quantity;
Did you round your numbers?

2024-07-12 10:44 UTC, MichailZyusko commented on book/src/order/order.service.ts
> +  }
What U should return in case if your Book with {id} doesn't exists?

2024-07-12 10:44 UTC, MichailZyusko commented on book/test/app.e2e-spec.ts
> +      .expect('Hello World!');
Are you sure that this test works well?

2024-07-12 10:44 UTC, MichailZyusko commented on docker-compose.yml
> +      - 5454:5432
Do you have port in your .env file?

2024-07-12 10:44 UTC, MichailZyusko commented on docker-compose.yml
> +      - backend
Where health check?

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/.eslintrc.js
DRY

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/auth/auth.controller.ts
> +    @Inject('USER_SERVICE') private readonly user_client: ClientProxy,
```suggestion
    @Inject('USER_SERVICE') private readonly userClient: ClientProxy,
```

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/auth/auth.module.ts
> +    // },
Let's remove unused code

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/auth/auth.controller.ts
> +  @UsePipes(new ValidationPipe({ transform: true }))
We can use validation Pipe globally

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/auth/dto/createUser.dto.ts
> +}
It's a part of CreateUserDto

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/common/dto/book.dto.ts
DRY! Let's move into shared folder or npm package

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/common/dto/user.dto.ts
> +}
We have same one into gateway/src/auth/dto/createUser.dto.ts

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/common/dto/user.dto.ts
> +}
Use utility types Readonly + Partial

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/common/guard/auth.guard.ts
> +    const token = this.extractTokenFromHeader(request);
Do we support cookies?

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/controllers/book.controller.ts
> +    await this.redisService.set(cachedKey, JSON.stringify(response.data), 3600);
Magic number 3600

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/controllers/book.controller.ts
> +    private readonly redisService: RedisService,
[read here more about it](https://docs.nestjs.com/techniques/caching)

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/controllers/book.controller.ts
> +    );
Not sure about error handling here

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/controllers/order.controller.ts
> +    console.log('i am in the order in the gaeway');
Do we really wanna have it?

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/redis/redis.module.ts
> +          //password: configService.get<string>('REDIS_PASSWORD'),
Let's remove unused comments

2024-07-12 10:44 UTC, MichailZyusko commented on user/src/main.ts
> +import * as dotenv from 'dotenv';
Why we are using dotenv instead of config service

2024-07-12 10:44 UTC, MichailZyusko commented on user/src/user.service.ts
> +    const hashedPassword = await bcrypt.hash(params.password, 10);
Read more about rainbow tables

2024-07-12 10:44 UTC, MichailZyusko commented on gateway/src/auth/auth.service.ts
Do we have refresh token?

2024-07-15 07:43 UTC, S-MOHSEN-SH commented on book/src/app.module.ts
> +        host: configService.get<string>('POSTGRES_HOST'),
Yes, it's possible but I have done something similar to it in the User microservice and connected it to MongoDB through this method that you're implying.

2024-07-15 07:49 UTC, S-MOHSEN-SH commented on gateway/src/auth/dto/createUser.dto.ts
> +  password: string;
I will implement this at the end of this task, because testing with small password is easier but great point

2024-07-15 08:00 UTC, S-MOHSEN-SH commented on book/src/book/book.controller.ts
> +  }
Status code 204 (No content ) but i implemented it in the corresponding controller in the gateway microservice

2024-07-15 08:11 UTC, S-MOHSEN-SH commented on book/src/order/order.controller.ts
No, in the original task, it was not a requirement to update orders . Just create and delete and of course getting all orders

2024-07-15 08:20 UTC, S-MOHSEN-SH commented on book/test/app.e2e-spec.ts
> +      .expect('Hello World!');
I forgot to delete the default test folder, i haven't written any testing for it yet. In the future i will implement testing as well.

2024-07-15 09:20 UTC, S-MOHSEN-SH commented on gateway/src/common/dto/user.dto.ts
> +}
I brought all of the DTOs to the common folder

2024-07-15 09:25 UTC, S-MOHSEN-SH commented on book/src/order/order.controller.ts
> +  }
Not yet, it was not implemented in the task however it sounds like a good idea. Will be implemented later

2024-07-15 09:32 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
will be implemented

2024-07-15 09:46 UTC, S-MOHSEN-SH commented on gateway/src/common/guard/auth.guard.ts
> +    const token = this.extractTokenFromHeader(request);
No, it's a simple authentication with Bearer.

2024-07-15 13:39 UTC, S-MOHSEN-SH commented on book/.eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
I haven't implemented any custom linters. Will be considered later

2024-07-15 14:08 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +    private readonly redisService: RedisService,
for now I will implement Redis with the simplest style, after consultation with my mentor, if he deems it necessary, i will implement this proposed way

2024-07-15 14:43 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +    }, 0);
For now, we won't touch it but after consultation with my mentor, we will decide to use aggregate functions or to continue as it is

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/.eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
Do it now, every of this rule should be on.

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/book/book.controller.ts
> +  async create(@Body() createBookDto: CreateBookDto) {
No return value, enable needed rule on config

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/common/entity/book.model.ts
> +export class Book extends Model<Book> {
Rename to BookModel. Each class should be understandable in the code

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/common/entity/order-item.model.ts
> +  price: number;
@S-MOHSEN-SH Please answer on each of the review comment. If changes done - than write down it.

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/common/entity/order-item.model.ts
> +  price: number;
Book have price, but why order have price?

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/common/entity/order.model.ts
> +  totalPrice: number;
Your price stored in the book, order-item and order. Duplicated, should be handled by join.

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/common/entity/book.model.ts
> +  available: boolean;
HasMany order items

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/common/dto/order.dto.ts
> +class CreateOrderItemDto {
1 class per file

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/common/enum/role.enum.ts
> +export enum Role {
Is it used?

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.controller.ts
> +  }
Do it after fix of review

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.controller.ts
> +  async findOneOrder(@Param('id') id: number) {
fix return

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +    const orderDate = new Date();
should be autogenerated

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +    }, 0);
do it

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +      totalPrice: Math.round(totalPrice * 100) / 100,
I don't understand

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +    return this.findOneOrder(order.id);
why find one more time?

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +  async createOrder(createOrderDto: CreateOrderDto): Promise<Order> {
no transaction

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +    const bookPrices = books.reduce((acc, book) => {
use Map instead

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +  async deleteOrder(id: number): Promise<void> {
no transaction

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/order/order.service.ts
> +  async deleteOrder(id: number): Promise<void> {
better use on delete cascade

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/src/app.module.ts
> +        synchronize: true,
@S-MOHSEN-SH please answer if comment is implemented or not and why

2024-07-15 18:53 UTC, IlyaRazuvaev commented on book/tsconfig.json
> +    "noImplicitAny": false,
do not use approach of disable checks

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.controller.ts
> +      throw new Error(`Registration failed: ${error.message}`);
no need, it broke all error messages from server, it will always throw internal error instead of normal

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +  async getToken(
use model, a lot of params is bad

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +  // async getToken(
delete if not needed

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +    return { user, token };
no need to return user

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +    return { user, token };
no need to return user

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +  ): Promise<{ access_token: string; refresh_token: string }> {
use model instead of manual interface

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +        expiresIn: '15m',
magic number

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +        expiresIn: '7d',
magic number

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +      const payload = await this.jwtService.verifyAsync(refreshToken, {
implement your own jwt service

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/auth/auth.service.ts
> +  async getToken(
Should be private?

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/common/dto/order.dto.ts
> +class CreateOrderItemDto {
one class - one file

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/common/guard/auth.guard.ts
> +      request['user'] = payload;
fix this by appropriate interface

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/common/constants.ts
> +  book: 'book',
no need to store it, It will never change

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +    private readonly redisService: RedisService,
Do it

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +    const cachedKey = 'all-books';
constant

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +      console.error('Error occurred while fetching the books:', error);
clear

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +        `Failed to fetch the books: ${error.response.data.message}`,
no need for things like this

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +  @UseGuards(JwtAuthGuard)
too big controllers

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/common/decorator/role.decorator.ts
> +export const Roles = (...roles: string[]) => SetMetadata(ROLES_KEY, roles);
not string

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +      const response = await firstValueFrom(
why you use firstValueFrom?

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +      await this.redisService.set(cachedKey, JSON.stringify(response), 3600);
magic number

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +    const pattern = `Book_*_${createBookDto.title}`;
title not unique, delete cache on create

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +      const response = await firstValueFrom(
should  clear cache

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +    const cachedKey = `Book_${id}`;
no need to cache one book, only all

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/book.controller.ts
> +  async remove(@Param('id') id: number) {
should clear cache

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/order.controller.ts
> +        `${this.configService.get<string>('ORDER_SERVICE_URL')}/${urlConstants.order}/${id}`,
user can not see orders that created not by him, but admin can

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/order.controller.ts
> +  async deleteOrder(@Param('id') id: number) {
he can delete any order

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/user.controller.ts
> +    private readonly jwtService: JwtService,
delete

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/redis/redis.service.ts
> +  async findandDeleteOldStuff(bookInfo: string) {
rename

2024-07-15 18:53 UTC, IlyaRazuvaev commented on mailer/src/interface/mail.interface.ts
> +  html: string;
use email templates stored in the mailer service

2024-07-15 18:53 UTC, IlyaRazuvaev commented on mailer/src/app.controller.ts
> +      console.error('There was a problem with sending email', error);
delete catch

2024-07-15 18:53 UTC, IlyaRazuvaev commented on mailer/src/app.service.ts
> +    // const transporter = nodemailer.createTransport({
what is it?*

2024-07-15 18:53 UTC, IlyaRazuvaev commented on mailer/src/main.ts
> +        urls: ['amqp://localhost:5672'],
magic number

2024-07-15 18:53 UTC, IlyaRazuvaev commented on mailer/.dockerignore
> +**/.git
where is docker file?

2024-07-15 18:53 UTC, IlyaRazuvaev commented on user/src/common/dto/user.dto.ts
> +  password: string;
no decorators

2024-07-15 18:53 UTC, IlyaRazuvaev commented on user/src/common/enum/user.enum.ts
> +export enum Role {
is it needed?

2024-07-15 18:53 UTC, IlyaRazuvaev commented on user/src/user.service.ts
> +    return newUser.save();
no need to return cached password

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/order.controller.ts
> +  @Post()
should be 201 status

2024-07-15 18:53 UTC, IlyaRazuvaev commented on user/src/user.controller.ts
> +    @Payload() data: { userId: string; params: UpdateUserDto },
interface

2024-07-15 18:53 UTC, IlyaRazuvaev commented on user/src/user.service.ts
> +  async updateUser(userId: string, params: UpdateUserDto): Promise<User> {
should compare password

2024-07-15 18:53 UTC, IlyaRazuvaev commented on user/src/user.service.ts
> +    return user;
never return passwords

2024-07-15 18:53 UTC, IlyaRazuvaev commented on gateway/src/controllers/user.controller.ts
> +  @Delete('delete/:id')
user can not delete any user

2024-07-15 18:53 UTC, IlyaRazuvaev commented on user/src/user.service.ts
> +  async deleteUser(userId: string): Promise<string> {
should compare password if done by user

2024-07-15 18:53 UTC, IlyaRazuvaev commented on docker-compose.yml
> +services:
no docker for microserices

2024-07-15 20:27 UTC, S-MOHSEN-SH commented on book/.eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
Done!

2024-07-15 20:31 UTC, S-MOHSEN-SH commented on book/src/app.module.ts
> +        synchronize: true,
The issue was raised in a way that in some specific situations ,synchronization could cause problems and would cost us the entire data. However because we are not dealing with very sensitive task, i didn't not implement it false.

2024-07-15 20:32 UTC, S-MOHSEN-SH commented on book/src/book/book.controller.ts
> +    @Body() updateBookDto: Partial<CreateBookDto>,
Done!

2024-07-15 20:32 UTC, S-MOHSEN-SH commented on book/src/book/book.service.ts
> +  async findAll(): Promise<Book[]> {
Done!

2024-07-15 20:32 UTC, S-MOHSEN-SH commented on book/src/book/book.service.ts
> +    const book = await this.findOne(id);
Done!

2024-07-15 20:33 UTC, S-MOHSEN-SH commented on book/src/book/book.service.ts
> +  async remove(id: number): Promise<void> {
Done!

2024-07-15 20:38 UTC, S-MOHSEN-SH commented on book/src/common/entity/order-item.model.ts
> +  price: number;
It was discussed and we came to conclusion to not implement it yet, because we are taking this task that far. However , if we want to develop this app in a way that a user can order book which will be available in the future, then pre-ordering should be implemented. 

order has a final price and order-item has a price which can be the total price per one product. For example user can order 10 of one book. so the price for that particular item would be multiplied by 10 times. ( it can be removed from the entity, its existence is not essential )

2024-07-15 20:38 UTC, S-MOHSEN-SH commented on book/src/main.ts
> +  await app.listen(5002);
Done!

2024-07-15 20:41 UTC, S-MOHSEN-SH commented on book/src/common/entity/order-item.model.ts
> +  quantity: number;
Done!

2024-07-15 20:41 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +      return acc + bookPrice * item.quantity;
Done!

2024-07-15 20:41 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +  }
It will throw an error

2024-07-15 20:48 UTC, S-MOHSEN-SH commented on docker-compose.yml
> +      - 5454:5432
Done!

2024-07-15 20:48 UTC, S-MOHSEN-SH commented on docker-compose.yml
> +      - backend
Done!

2024-07-15 20:49 UTC, S-MOHSEN-SH commented on gateway/.eslintrc.js
Done!

2024-07-15 20:49 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.controller.ts
> +    @Inject('USER_SERVICE') private readonly user_client: ClientProxy,
Done !

2024-07-15 20:49 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.module.ts
> +    // },
Done!

2024-07-15 20:50 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.controller.ts
> +  @UsePipes(new ValidationPipe({ transform: true }))
Done!

2024-07-15 20:50 UTC, S-MOHSEN-SH commented on gateway/src/auth/dto/createUser.dto.ts
> +}
It is separated them

2024-07-15 20:52 UTC, S-MOHSEN-SH commented on gateway/src/common/dto/book.dto.ts
It is moved in the common folder

2024-07-15 20:52 UTC, S-MOHSEN-SH commented on gateway/src/common/dto/user.dto.ts
> +}
Done!

2024-07-15 20:58 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +    private readonly redisService: RedisService,
In this case, all or maybe most of the implementation of Redis that I have done will be deleted (including your comments about them) and I will follow the cache-manager and other related topics in this link

2024-07-15 21:44 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +    );
I am using firstValueFrom to convert observable to promise so that we can work with it 
https://rxjs.dev/api/index/function/firstValueFrom
We can catch the error by try-catch block

2024-07-15 21:44 UTC, S-MOHSEN-SH commented on gateway/src/controllers/order.controller.ts
> +    console.log('i am in the order in the gaeway');
Done!

2024-07-15 21:44 UTC, S-MOHSEN-SH commented on gateway/src/redis/redis.module.ts
> +          //password: configService.get<string>('REDIS_PASSWORD'),
Removed!

2024-07-15 21:45 UTC, S-MOHSEN-SH commented on user/src/main.ts
> +import * as dotenv from 'dotenv';
It was there by mistake. Removed !

2024-07-15 21:45 UTC, S-MOHSEN-SH commented on book/.eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
It is Done!

2024-07-15 21:55 UTC, S-MOHSEN-SH commented on book/src/common/entity/order-item.model.ts
> +  price: number;
> How to handle a case when book is pre-ordered ?

It was discussed and we came to conclusion to not implement it yet, because we are taking this task that far. However , if we want to develop this app in a way that a user can order book which will be available in the future, then pre-ordering should be implemented.

2024-07-15 22:08 UTC, S-MOHSEN-SH commented on book/src/common/dto/order.dto.ts
> +class CreateOrderItemDto {
fixed !

2024-07-15 22:09 UTC, S-MOHSEN-SH commented on book/src/common/enum/role.enum.ts
> +export enum Role {
deleted !

2024-07-15 22:11 UTC, S-MOHSEN-SH commented on book/src/order/order.controller.ts
> +  async findOneOrder(@Param('id') id: number) {
fixed!

2024-07-15 22:15 UTC, S-MOHSEN-SH commented on book/src/common/entity/book.model.ts
> +export class Book extends Model<Book> {
fixed!

2024-07-15 22:26 UTC, S-MOHSEN-SH commented on docker-compose.yml
> +services:
I deleted them and i am running the microservices locally through terminal because when i sun them through docker-compose , they will not connect to their database. 
When i fix it , everything will be run through docker-compose and docker

2024-07-16 07:57 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +    const orderDate = new Date();
fixed with   @Default(DataType.NOW)

2024-07-16 08:24 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +    }, 0);
Done!

const totalPrice = await this.orderItemModel.findAll({
      attributes: [
        [
          this.orderItemModel.sequelize.fn(
            'SUM',
            this.orderItemModel.sequelize.col('quantity * book.price'),
          ),
          'totalPrice',
        ],
      ],
      include: [
        {
          model: this.bookModel,
          attributes: [],
        },
      ],
      where: { orderId: order.id },
      raw: true,
    });

    order.totalPrice = totalPrice[0].price;
    await order.save();

2024-07-16 08:27 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +      totalPrice: Math.round(totalPrice * 100) / 100,
I tried to round the total price , but since we have changed the way we calculate the total price, then maybe it's not necessary anymore.

2024-07-16 08:28 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +    return this.findOneOrder(order.id);
I just wanted to return the order by making sure it is functional and could be retrieved by order id. It's not a crucial part of the code. I can simply return order.

2024-07-16 09:12 UTC, S-MOHSEN-SH commented on book/src/common/entity/book.model.ts
> +  available: boolean;
Fixed!

2024-07-16 11:13 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +  async createOrder(createOrderDto: CreateOrderDto): Promise<Order> {
implemented .
Do we need it only for creating orders ? Or shall i implement it for creating books as well ?

2024-07-16 11:14 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +    const bookPrices = books.reduce((acc, book) => {
Already aggregation functions have been used instead for calculation of total price

2024-07-16 11:23 UTC, S-MOHSEN-SH commented on book/src/order/order.service.ts
> +  async deleteOrder(id: number): Promise<void> {
on delete cascade was implemented. 
transaction was implemented

2024-07-16 11:30 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +  // async getToken(
done!

2024-07-16 11:37 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +    return { user, token };
Done!

2024-07-16 11:37 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +    return { user, token };
Done!

2024-07-16 11:54 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +        expiresIn: '15m',
done!

2024-07-16 11:54 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +        expiresIn: '7d',
done!

2024-07-16 11:57 UTC, S-MOHSEN-SH commented on gateway/src/common/dto/order.dto.ts
> +class CreateOrderItemDto {
done!

2024-07-16 11:59 UTC, S-MOHSEN-SH commented on gateway/src/common/constants.ts
> +  book: 'book',
It was your suggestion to do so in the first place. I will delete them and put this constant in the URL in the .env file.

2024-07-16 12:04 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +  @UseGuards(JwtAuthGuard)
I can delete try-catch block that i have implemented after each http request to make it smaller. according to your previous comment, they are not so needed. Shall I ?

2024-07-16 12:06 UTC, S-MOHSEN-SH commented on gateway/src/common/decorator/role.decorator.ts
> +export const Roles = (...roles: string[]) => SetMetadata(ROLES_KEY, roles);
fixed!

2024-07-16 12:09 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +      const response = await firstValueFrom(
I am using firstValueFrom to convert observable to promise so that we can work with it
https://rxjs.dev/api/index/function/firstValueFrom
We can catch the error by try-catch block

2024-07-16 12:09 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +      await this.redisService.set(cachedKey, JSON.stringify(response), 3600);
fixed!

2024-07-16 12:12 UTC, S-MOHSEN-SH commented on gateway/src/controllers/user.controller.ts
> +    private readonly jwtService: JwtService,
done!

2024-07-16 12:14 UTC, S-MOHSEN-SH commented on gateway/src/redis/redis.service.ts
> +  async findandDeleteOldStuff(bookInfo: string) {
done!

2024-07-16 12:19 UTC, S-MOHSEN-SH commented on mailer/src/app.controller.ts
> +      console.error('There was a problem with sending email', error);
Done!

2024-07-16 13:24 UTC, S-MOHSEN-SH commented on user/src/common/enum/user.enum.ts
> +export enum Role {
deleted!

2024-07-18 06:34 UTC, S-MOHSEN-SH commented on book/src/book/book.controller.ts
> +  async create(@Body() createBookDto: CreateBookDto) {
If you mean to specify the outcome of this Post request, then done!

2024-07-18 06:35 UTC, S-MOHSEN-SH commented on book/src/common/entity/order.model.ts
> +  totalPrice: number;
Entities updated. Price only exist in bookModel and total price of  all orders in final order

2024-07-18 07:13 UTC, S-MOHSEN-SH commented on book/tsconfig.json
> +    "noImplicitAny": false,
"strictNullChecks": true,
    Done!

2024-07-18 07:19 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +  async getToken(
Yes, it's a good idea to make getToken private because it is purposefully used only in AuthService.

2024-07-18 07:22 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +  ): Promise<{ access_token: string; refresh_token: string }> {
Done!

2024-07-18 09:20 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.service.ts
> +      const payload = await this.jwtService.verifyAsync(refreshToken, {
Done!

2024-07-19 09:21 UTC, S-MOHSEN-SH commented on gateway/src/auth/auth.controller.ts
> +      throw new Error(`Registration failed: ${error.message}`);
done !

2024-07-19 09:50 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +    const cachedKey = 'all-books';
Done!

2024-07-19 09:56 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +      console.error('Error occurred while fetching the books:', error);
done!

2024-07-19 09:57 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +        `Failed to fetch the books: ${error.response.data.message}`,
Deleted !

2024-07-19 10:02 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +    const cachedKey = `Book_${id}`;
deleted !

2024-07-19 11:58 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +    const pattern = `Book_*_${createBookDto.title}`;
fixed!

2024-07-19 12:11 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +      const response = await firstValueFrom(
I assumed that all cache should be deleted

2024-07-19 12:12 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +  async remove(@Param('id') id: number) {
yet again , i assumed all data in cache should be deleted !

2024-07-20 18:13 UTC, endlesslydivided commented on book/src/common/entity/order.model.ts
> +export class Order extends Model<Order> {
```javascript
@Table
export class Order extends Model<InferAttributes<Order>, InferCreationAttributes<Order>>
``` 

And don't forget about imports of these InferAttributes and InferCreationAttributes from package!

Also make same changes for all entity models!

2024-07-22 08:02 UTC, S-MOHSEN-SH commented on mailer/src/app.service.ts
> +    // const transporter = nodemailer.createTransport({
deleted !

2024-07-22 08:06 UTC, S-MOHSEN-SH commented on mailer/src/main.ts
> +        urls: ['amqp://localhost:5672'],
used environmental variables for it

2024-07-22 08:08 UTC, S-MOHSEN-SH commented on user/src/common/dto/user.dto.ts
> +  password: string;
done!

2024-07-22 08:13 UTC, S-MOHSEN-SH commented on user/src/user.service.ts
> +    return newUser.save();
fixed !

2024-07-22 08:28 UTC, S-MOHSEN-SH commented on user/src/user.controller.ts
> +    @Payload() data: { userId: string; params: UpdateUserDto },
Done!

2024-07-22 08:46 UTC, S-MOHSEN-SH commented on user/src/user.service.ts
> +  async updateUser(userId: string, params: UpdateUserDto): Promise<User> {
Done!

2024-07-22 08:47 UTC, S-MOHSEN-SH commented on user/src/user.service.ts
> +    return user;
Done!

2024-07-22 08:49 UTC, S-MOHSEN-SH commented on gateway/src/controllers/user.controller.ts
> +  @Delete('delete/:id')
fixed by Role decorator

2024-07-22 08:50 UTC, S-MOHSEN-SH commented on user/src/user.service.ts
> +  async deleteUser(userId: string): Promise<string> {
Done!

2024-07-22 12:48 UTC, S-MOHSEN-SH commented on book/src/common/entity/order.model.ts
> +export class Order extends Model<Order> {
fixed !

2024-07-22 13:47 UTC, S-MOHSEN-SH commented on mailer/src/interface/mail.interface.ts
> +  html: string;
Done!

2024-07-22 15:00 UTC, S-MOHSEN-SH commented on gateway/src/common/guard/auth.guard.ts
> +      request['user'] = payload;
Done!

2024-07-22 15:03 UTC, S-MOHSEN-SH commented on mailer/.dockerignore
> +**/.git
I don't think i should put DockerFile in the dockerignore, shall i ?

2024-07-22 15:17 UTC, S-MOHSEN-SH commented on gateway/src/controllers/book.controller.ts
> +  @UseGuards(JwtAuthGuard)
I devided it into service and controller

2024-07-23 09:34 UTC, S-MOHSEN-SH commented on gateway/src/controllers/order.controller.ts
> +        `${this.configService.get<string>('ORDER_SERVICE_URL')}/${urlConstants.order}/${id}`,
implemented !

2024-07-23 09:35 UTC, S-MOHSEN-SH commented on gateway/src/controllers/order.controller.ts
> +  async deleteOrder(@Param('id') id: number) {
Not sure if i fully get the situation !

2024-07-23 09:37 UTC, S-MOHSEN-SH commented on gateway/src/controllers/order.controller.ts
> +  @Post()
done!

2024-07-25 15:55 UTC, merged